using Microsoft.Data.Sqlite;

namespace SylvaNote.Core.DataAccess.Migrations
{
    // Client-only derived cache (note_link/FTS category): generated by the frontend
    // from the full image, never synced, rebuilt lazily when missing.
    public sealed class Db003_AttachmentThumbnail : IMigration
    {
        public int Version => 3;

        public void Up(SqliteConnection connection)
        {
            using SqliteCommand command = connection.CreateCommand();
            command.CommandText = @"
                CREATE TABLE attachment_thumbnail (
                    attachment_id TEXT NOT NULL PRIMARY KEY REFERENCES attachment (id) ON DELETE CASCADE,
                    data          BLOB NOT NULL
                );
            ";
            command.ExecuteNonQuery();
        }
    }
}
